### PR TITLE
Use exit() for ajax.

### LINKED ISSUE #53: Use exit() or die() in ajax not wp_die as it prints HTML.

### PR DESCRIPTION
**Pull request by Pross**
Fixes #53

### CODE REVIEW

**Comment by octalmage** [comment]
On this page they state that wp_die should be used: 

> Notice the use of wp_die(), instead of die() or exit(). Most of the time you should be using wp_die() in your Ajax callback function. This provides better integration with WordPress and makes it easier to test your code.

https://codex.wordpress.org/AJAX_in_Plugins

and If you look at this function (which we should probably be using): 

https://core.trac.wordpress.org/browser/tags/4.5.3/src/wp-includes/functions.php#L3034

It looks like it also uses wp_die.

**Comment by Pross** [comment]
True, if you use wp_send_json or the success/fail functions you will have to bump the minimum to 3.5.0 remember.

**Comment by octalmage** [comment]
Hmm, I think it would be worth it. Looking at those functions, they do a number of things to help with sending JSON to the browser, and we've had some issues with JSON parsing. I'm curious if it would help.

**Comment by octalmage** [comment]
I created #57 to resolve this with a few other changes. Thanks!

**Pull request closed without merging**
