### PR TITLE
Versions array instead of hardcoded HTML

### PR DESCRIPTION
**Pull request by Pross**
Adding new PHP versions meant editing HTML, using an array makes more sense, included a filter.

### CODE REVIEW

**Comment by jrfnl** [comment]
:+1: 

Two questions:
1. Why not have the base array as a class property ?
2. What about adding PHP 7.1 ?

**Comment by Pross** [comment]
1. There is no construct so was unsure how to add it.
2. I was going to test 7.1, thats when I noticed the versions are hardcoded.

**Comment by jrfnl** [comment]
Re 1: Sorry, I might have been unclear - I meant to leave the function in place for the filter (or move it down to where the array is actually used/retrieved), but have the array of versions as a class property.
Whether or not the class has a constructor is irrelevant in that case.

Re 2: FYI - the PHPCompatibility standard already includes most checks for PHP 7.1 compatibility in the latest releases and has been tested against PHP 7.1.

**Comment by Pross** [comment]
The init function is static, so would take another function just to load the array into a class property.

Updating to 7.1 should be a separate PR surely.

**Comment by jrfnl** [comment]
> The init function is static, so would take another function just to load the array into a class property.

I have no idea what you mean. As long as it's a array without function calls in it, you can define it whether there is a constructor or not. That really has nothing to do with it. No other function call needed.

**Pull request merged**
